### ISSUE TITLE
added some options but last one not working

### ISSUE THREAD

**Issue by justinw78** [mgafner/homewizard-web-remote#6]
[homewizard.txt](https://github.com/mgafner/homewizard-web-remote/files/1880880/homewizard.txt)

Hello,

Thnx for your good code.

I have changed some only the last one i cant get it to work. Can you please check the code a little?

getstatus()
# ------------------------------------------------------------------------------
#
# Description:  return the status of a sensor
#
# Parameter  :  none
#
# Output     :  logging
#
{
  update_cache_check
  echo `cat $PROFILEDIR/homewizard.json | jq '.kakusensors | .[] | select(.name=='\"$1\"') | .status'`
} 

isn't working All other what i have added works:)

Thnx and greetings   justin

**Comment by mgafner** [comment]
Nice! I cannot test it right now but I guess you should add the option -M in the getopts-loop and a call for getstatus().
